VALID_USERNAME = 'pyhtonautomation@gmail.com'
VALID_PASSWORD = 'exa46856'
INVALID_USERNAME = 'invalid'
FIELD_USERNAME='#loginusername'
FIELD_PASS='#loginpassword'
LOGIN_BUTTON='#logInModal > div > div > div.modal-footer > button.btn.btn-primary'
LOGOUT_BUTTON= '#logout2'
USER_LOG = '#nameofuser'