CONTACT_EMAIL = 'prueba@123.com'
CONTACT_NAME = 'prueba'
INVALID_USERNAME = 'invalid'
LOGIN_URL = 'https://www.demoblaze.com/'
MESSAGE_TEXT = 'prueba envio mensaje'
VALID_USERNAME = 'pyhtonautomation@gmail.com'
VALID_PASSWORD = 'exa46856'
