CONTACT_EMAIL_FIELD = '#recipient-email'
CONTACT_NAME_FIELD = '#recipient-name'
MESSAGE_TEXT = '#message-text'
SEND_MESSAGE_BTN = '#exampleModal > div > div > div.modal-footer > button.btn.btn-primary'
CONTACT_EMAIL = 'prueba@123.com'
CONTACT_NAME = 'prueba'
MESSAGE = 'prueba envio mensaje'
